# order of menu items, used by CommandAdapter

MAIN = [
  "org.strykeforce.thirdcoast.telemetry.tct.TalonModeCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.ServoModeCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.DioModeCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.QuitCommand",
]

TALON = [
"org.strykeforce.thirdcoast.telemetry.tct.talon.ListCommand",
"org.strykeforce.thirdcoast.telemetry.tct.talon.SelectCommand",
"org.strykeforce.thirdcoast.telemetry.tct.talon.ConfigModeCommand",
"org.strykeforce.thirdcoast.telemetry.tct.talon.InspectCommand",
"org.strykeforce.thirdcoast.telemetry.tct.talon.RunCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.LoadConfigsCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.SaveConfigCommand",
]

TALON_CONFIG = [
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.SelectOperatingModeCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.ClosedLoopConfigCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.OutputConfigCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.EncoderConfigCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.LimitConfigCommand",
]

TALON_CONFIG_CL = [
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.cl.PCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.cl.ICommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.cl.DCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.cl.FCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.cl.IZoneCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.cl.AllowableClosedLoopErrorCommand",
]

TALON_CONFIG_ENC = [
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.SelectTypeCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.SetPositionCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.ReverseSensorCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.ReverseOutputCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.VelocityMeasurementPeriodCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.VelocityMeasurementWindowCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.GeneralFrameRateCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.FeedbackFrameRateCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.QuadEncoderFrameRateCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.AnalogTempVbatFrameRateCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.enc.PulseWidthFrameRateCommand",
]

TALON_CONFIG_LIM = [
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.lim.ForwardSoftLimitCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.lim.EnableForwardSoftLimitCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.lim.ReverseSoftLimitCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.lim.EnableReverseSoftLimitCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.lim.LimitSwitchEnabled",
]

TALON_CONFIG_OUT = [
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.out.VoltageRampRateCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.out.ClosedLoopRampRateCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.out.PeakOutputVoltageCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.out.NominalOutputVoltageCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.out.CurrentLimitCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.talon.config.out.BrakeInNeutralCommand",
]

SERVO = [
  "org.strykeforce.thirdcoast.telemetry.tct.servo.SelectServoCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.servo.RunServoCommand",
]

DIO = [
  "org.strykeforce.thirdcoast.telemetry.tct.dio.InspectDigitalInputsCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.dio.SelectDigitalOutputCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.dio.RunDigitalOutputCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.dio.PulseDigitalOutputCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.dio.PwmDigitalOutputCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.dio.DemoPulseDigitalOutputCommand",
  "org.strykeforce.thirdcoast.telemetry.tct.dio.DemoPwmDigitalOutputCommand"
]
